# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Категория', max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Введите название', max_length=100, verbose_name='Название')),
                ('availability', models.CharField(choices=[('is', 'В наличии'), ('c', 'Под заказ')], default=('is', 'В наличии'), max_length=100, verbose_name='Наличие')),
                ('photo', models.ImageField(upload_to=shop.models.upload_path, verbose_name='Главное фото')),
                ('photo1', models.ImageField(blank=True, upload_to=shop.models.upload_path, verbose_name='Фото 1')),
                ('photo2', models.ImageField(blank=True, upload_to=shop.models.upload_path, verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, upload_to=shop.models.upload_path, verbose_name='Фото 3')),
                ('photo4', models.ImageField(blank=True, upload_to=shop.models.upload_path, verbose_name='Фото 4')),
                ('photo5', models.ImageField(blank=True, upload_to=shop.models.upload_path, verbose_name='Фото 5')),
                ('video', models.URLField(blank=True, verbose_name='Видеообзор')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('date', models.DateField(default=datetime.datetime(2016, 7, 11, 12, 49, 56, 61056, tzinfo=utc), editable=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена в розницу')),
                ('price_opt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена оптом')),
                ('diagonal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Диагональ')),
                ('resolution', models.CharField(blank=True, max_length=50, verbose_name='Разрешение экрана')),
                ('display_other', models.CharField(blank=True, max_length=200, verbose_name='Дисплей дополнительно')),
                ('wireless', models.CharField(blank=True, max_length=500, verbose_name='Беспроводные возможности')),
                ('interfaces', models.CharField(blank=True, max_length=500, verbose_name='Интерфейсы и подключения')),
                ('battery', models.IntegerField(blank=True, default=0, verbose_name='Ёмкость батареи')),
                ('camera', models.IntegerField(blank=True, default=0, verbose_name='Размер камеры')),
                ('camera_other', models.CharField(blank=True, max_length=100, verbose_name='Камера дополнитьльно')),
                ('osystem', models.CharField(blank=True, max_length=500, verbose_name='Операционная система')),
                ('count_core', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6'), (8, '8'), (12, '12')], default=(1, '1'), verbose_name='Количесво ядер')),
                ('core_other', models.CharField(blank=True, max_length=200, verbose_name='Процессор')),
                ('ram', models.IntegerField(blank=True, default=0, verbose_name='Оперативная память')),
                ('memory', models.IntegerField(blank=True, default=0, verbose_name='Внутреняя память')),
                ('memory_other', models.CharField(blank=True, max_length=200, verbose_name='Память дополнительно')),
                ('other', models.CharField(blank=True, max_length=200, verbose_name='Дополнительно')),
                ('standards', models.CharField(blank=True, max_length=100, verbose_name='Стандарты и техгологии')),
                ('front_camera', models.IntegerField(blank=True, default=0, verbose_name='Размер фронтальной камеры')),
                ('front_camera_other', models.CharField(blank=True, max_length=100, verbose_name='Камера фронтальная дополнительно')),
                ('sim_count', models.IntegerField(blank=True, default=0, verbose_name='Количество сим')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=shop.models.get_uniq_name)),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Phone')),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.phone',),
        ),
        migrations.AddField(
            model_name='phone',
            name='link_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
    ]
