# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160716_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 14, 16, 35, 920789, tzinfo=utc), editable=False),
        ),
    ]
