# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160716_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tablet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='phone',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 14, 22, 38, 762887, tzinfo=utc), editable=False),
        ),
    ]
